"""add last_reconciled_at and n_credits to position_state

Revision ID: 93c9ff214a61
Revises: ffa04ebd15ab
Create Date: 2026-05-29 06:55:58.904475

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '93c9ff214a61'
down_revision: str | Sequence[str] | None = 'ffa04ebd15ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_state', sa.Column('last_reconciled_at', sa.BigInteger(), nullable=True))
    op.add_column('position_state', sa.Column('n_credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position_state', 'n_credits')
    op.drop_column('position_state', 'last_reconciled_at')
    # ### end Alembic commands ###
