"""add reconcile_observation checkpoint table

Revision ID: a3ae9a60862a
Revises: 93c9ff214a61
Create Date: 2026-05-29 07:17:41.717066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ae9a60862a'
down_revision: Union[str, Sequence[str], None] = '93c9ff214a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconcile_observation',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('deployment_environment', sa.Text(), nullable=False),
    sa.Column('reserved_usdt', sa.Numeric(), nullable=False),
    sa.Column('realized_usdt', sa.Numeric(), nullable=False),
    sa.Column('n_offers', sa.Integer(), nullable=False),
    sa.Column('n_credits', sa.Integer(), nullable=False),
    sa.Column('observed_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('event_seq_fence', sa.BigInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reconcile_obs_acct_env_id', 'reconcile_observation', ['account_id', 'deployment_environment', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reconcile_obs_acct_env_id', table_name='reconcile_observation')
    op.drop_table('reconcile_observation')
    # ### end Alembic commands ###
