// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apikey.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, label, api_key, api_secret)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, label, api_key, api_secret, created_at, updated_at
`

type CreateAPIKeyParams struct {
	UserID    pgtype.UUID
	Label     string
	ApiKey    string
	ApiSecret []byte
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Label,
		arg.ApiKey,
		arg.ApiSecret,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.ApiKey,
		&i.ApiSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys
WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, user_id, label, api_key, api_secret, created_at, updated_at
FROM api_keys
WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.ApiKey,
		&i.ApiSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByUserID = `-- name: GetAPIKeyByUserID :one
SELECT id, user_id, label, api_key, api_secret, created_at, updated_at
FROM api_keys
WHERE user_id = $1
`

func (q *Queries) GetAPIKeyByUserID(ctx context.Context, userID pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByUserID, userID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.ApiKey,
		&i.ApiSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
