// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBillingRecord = `-- name: CreateBillingRecord :one
INSERT INTO billing_records (user_id, period_start, period_end, plan, amount, currency, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, period_start, period_end, plan, amount, currency, status, paid_at, created_at
`

type CreateBillingRecordParams struct {
	UserID      pgtype.UUID
	PeriodStart pgtype.Timestamptz
	PeriodEnd   pgtype.Timestamptz
	Plan        string
	Amount      float64
	Currency    string
	Status      string
}

func (q *Queries) CreateBillingRecord(ctx context.Context, arg CreateBillingRecordParams) (BillingRecord, error) {
	row := q.db.QueryRow(ctx, createBillingRecord,
		arg.UserID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Plan,
		arg.Amount,
		arg.Currency,
		arg.Status,
	)
	var i BillingRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Plan,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBillingByUser = `-- name: ListBillingByUser :many
SELECT id, user_id, period_start, period_end, plan, amount, currency, status, paid_at, created_at
FROM billing_records
WHERE user_id = $1 AND period_start >= $2
ORDER BY period_start DESC
LIMIT $3
`

type ListBillingByUserParams struct {
	UserID      pgtype.UUID
	PeriodStart pgtype.Timestamptz
	Limit       int32
}

func (q *Queries) ListBillingByUser(ctx context.Context, arg ListBillingByUserParams) ([]BillingRecord, error) {
	rows, err := q.db.Query(ctx, listBillingByUser, arg.UserID, arg.PeriodStart, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingRecord
	for rows.Next() {
		var i BillingRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Plan,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingByUserCursor = `-- name: ListBillingByUserCursor :many
SELECT id, user_id, period_start, period_end, plan, amount, currency, status, paid_at, created_at
FROM billing_records
WHERE user_id = $1
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListBillingByUserCursorParams struct {
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ID        pgtype.UUID
	Limit     int32
}

func (q *Queries) ListBillingByUserCursor(ctx context.Context, arg ListBillingByUserCursorParams) ([]BillingRecord, error) {
	rows, err := q.db.Query(ctx, listBillingByUserCursor,
		arg.UserID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingRecord
	for rows.Next() {
		var i BillingRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Plan,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingByUserFirst = `-- name: ListBillingByUserFirst :many
SELECT id, user_id, period_start, period_end, plan, amount, currency, status, paid_at, created_at
FROM billing_records
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListBillingByUserFirstParams struct {
	UserID pgtype.UUID
	Limit  int32
}

func (q *Queries) ListBillingByUserFirst(ctx context.Context, arg ListBillingByUserFirstParams) ([]BillingRecord, error) {
	rows, err := q.db.Query(ctx, listBillingByUserFirst, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingRecord
	for rows.Next() {
		var i BillingRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Plan,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
