// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConfigByUserID = `-- name: DeleteConfigByUserID :execrows
DELETE FROM user_configs
WHERE user_id = $1
`

func (q *Queries) DeleteConfigByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConfigByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConfigByUserID = `-- name: GetConfigByUserID :one
SELECT id, user_id, config, created_at, updated_at
FROM user_configs
WHERE user_id = $1
`

func (q *Queries) GetConfigByUserID(ctx context.Context, userID pgtype.UUID) (UserConfig, error) {
	row := q.db.QueryRow(ctx, getConfigByUserID, userID)
	var i UserConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConfig = `-- name: UpsertConfig :one
INSERT INTO user_configs (user_id, config)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET
  config = EXCLUDED.config,
  updated_at = now()
RETURNING id, user_id, config, created_at, updated_at
`

type UpsertConfigParams struct {
	UserID pgtype.UUID
	Config []byte
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) (UserConfig, error) {
	row := q.db.QueryRow(ctx, upsertConfig, arg.UserID, arg.Config)
	var i UserConfig
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
