// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (user_id, action, currency, amount, rate, period, offer_id, status, error_message)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, action, currency, amount, rate, period, offer_id, status, error_message, created_at
`

type CreateExecutionParams struct {
	UserID       pgtype.UUID
	Action       string
	Currency     string
	Amount       float64
	Rate         float64
	Period       int32
	OfferID      pgtype.Int8
	Status       string
	ErrorMessage pgtype.Text
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, createExecution,
		arg.UserID,
		arg.Action,
		arg.Currency,
		arg.Amount,
		arg.Rate,
		arg.Period,
		arg.OfferID,
		arg.Status,
		arg.ErrorMessage,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Currency,
		&i.Amount,
		&i.Rate,
		&i.Period,
		&i.OfferID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listExecutionsByUser = `-- name: ListExecutionsByUser :many
SELECT id, user_id, action, currency, amount, rate, period, offer_id, status, error_message, created_at
FROM executions
WHERE user_id = $1 AND created_at >= $2
ORDER BY created_at DESC
LIMIT $3
`

type ListExecutionsByUserParams struct {
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) ListExecutionsByUser(ctx context.Context, arg ListExecutionsByUserParams) ([]Execution, error) {
	rows, err := q.db.Query(ctx, listExecutionsByUser, arg.UserID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Currency,
			&i.Amount,
			&i.Rate,
			&i.Period,
			&i.OfferID,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
