// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateBillingRecord(ctx context.Context, arg CreateBillingRecordParams) (BillingRecord, error)
	CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error)
	DeleteConfigByUserID(ctx context.Context, userID pgtype.UUID) (int64, error)
	GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	GetAPIKeyByUserID(ctx context.Context, userID pgtype.UUID) (ApiKey, error)
	GetConfigByUserID(ctx context.Context, userID pgtype.UUID) (UserConfig, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListBillingByUser(ctx context.Context, arg ListBillingByUserParams) ([]BillingRecord, error)
	ListBillingByUserCursor(ctx context.Context, arg ListBillingByUserCursorParams) ([]BillingRecord, error)
	ListBillingByUserFirst(ctx context.Context, arg ListBillingByUserFirstParams) ([]BillingRecord, error)
	ListExecutionsByUser(ctx context.Context, arg ListExecutionsByUserParams) ([]Execution, error)
	ListExecutionsByUserCursor(ctx context.Context, arg ListExecutionsByUserCursorParams) ([]Execution, error)
	ListExecutionsByUserFirst(ctx context.Context, arg ListExecutionsByUserFirstParams) ([]Execution, error)
	ListVerifiedAPIKeys(ctx context.Context) ([]ApiKey, error)
	UpdateExchangeStatus(ctx context.Context, arg UpdateExchangeStatusParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) error
	UpsertConfig(ctx context.Context, arg UpsertConfigParams) (UserConfig, error)
}

var _ Querier = (*Queries)(nil)
