"""add legacy create_all tables (users, funding_candles, funding_stats, executions, billing_records)

Revision ID: 028cf1a1554e
Revises: a2b3c4d5e6f7
Create Date: 2026-06-23 02:33:58.483295

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '028cf1a1554e'
down_revision: str | Sequence[str] | None = 'a2b3c4d5e6f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_candles',
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.Text(), nullable=False),
    sa.Column('period_agg', sa.Text(), nullable=False),
    sa.Column('mts', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timeframe', 'period_agg', 'mts')
    )
    op.create_index('idx_funding_candles_mts', 'funding_candles', ['mts'], unique=False)
    op.create_table('funding_stats',
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('mts', sa.BigInteger(), nullable=False),
    sa.Column('frr', sa.Float(), nullable=True),
    sa.Column('avg_period', sa.Float(), nullable=True),
    sa.Column('funding_amount', sa.Float(), nullable=True),
    sa.Column('funding_amount_used', sa.Float(), nullable=True),
    sa.Column('funding_below_threshold', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'mts')
    )
    op.create_index('idx_funding_stats_mts', 'funding_stats', ['mts'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('plan', sa.Text(), server_default=sa.text("'free'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_table('billing_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan', sa.Text(), server_default=sa.text("'free'"), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_billing_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_billing_user_period', 'billing_records', ['user_id', 'period_start'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'success'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_executions_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_executions_user_created', 'executions', ['user_id', 'created_at'], unique=False)
    # NOTE: autogenerate also wants to drop fk_api_keys_user_profile,
    # fk_user_configs_user_profile, fk_user_profiles_user — these are DB-only FKs
    # (the models intentionally declare no model-level ForeignKey, see
    # accounts/tables.py). They are correct and must stay; stripped here.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # (upgrade did not drop the DB-only FKs, so downgrade must not re-create them)
    op.drop_index('idx_executions_user_created', table_name='executions')
    op.drop_table('executions')
    op.drop_index('idx_billing_user_period', table_name='billing_records')
    op.drop_table('billing_records')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_funding_stats_mts', table_name='funding_stats')
    op.drop_table('funding_stats')
    op.drop_index('idx_funding_candles_mts', table_name='funding_candles')
    op.drop_table('funding_candles')
    # ### end Alembic commands ###
