#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# bot vs FRR auto-renew A/B — sub-account B-arm setup.
# ADR: second-brain wiki/projects/bfx-funding-bot/decisions/2026-09-22-frr-baseline-ab-via-sub-account.md
# Review: backend/docs/research/2026-09-22-strategy-system-review.md §4
#
# Values land in a gitignored local env file (matches .gitignore `.env.*.local`)
# that the read-only loader scripts/report_ab_frr.py will consume. Nothing here
# touches the bot's runtime env, the vault, or CI secrets.
#
# Bitfinex UI paths below are the operator's best knowledge as of 2026-09-22 —
# they are NOT verified against the current site. Where a page or button is
# named differently, follow the page; the values to capture do not change.

cd "$(dirname "$0")/.."
ENV_FILE="${ENV_FILE:-backend/.env.ab-subaccount.local}"
TOTAL_STAGES=7
MIN_OFFER_USD=150      # venue minimum per offer
A_ARM_FLOOR=215        # 0.70 × T ≥ 150  ⇒  T ≥ 215 (I-CC cell concentration)

banner "bfx A/B — FRR auto-renew sub-account (B arm)"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Preflight — halt, NAV, split"
say "The A/B only makes sense while the bot is halted for the transfer and can"
say "lend afterwards. Check the durable halt first (ask the guard, not the env)."
step "On the VM: GET /admin/trading-status must show halted=true (persistent halt)."
step "Note the master account's fUST funding-wallet balance (NAV)."
ask BFX_AB_NAV_UST "Master funding wallet UST balance now (number):"
ask BFX_AB_A_ARM_TARGET_UST "A arm (bot) target UST to keep on master [≥ ${A_ARM_FLOOR}]:"
ask BFX_AB_B_ARM_AMOUNT_UST "B arm (FRR auto-renew) UST to move to sub-account [≥ ${MIN_OFFER_USD}]:"
if (( ${BFX_AB_A_ARM_TARGET_UST%.*} < A_ARM_FLOOR )); then
  warn "A arm < ${A_ARM_FLOOR}: cell_limit = 0.70×T < ${MIN_OFFER_USD} ⇒ every bot offer is blocked (I-CC)."
fi
if (( ${BFX_AB_B_ARM_AMOUNT_UST%.*} < MIN_OFFER_USD )); then
  warn "B arm < ${MIN_OFFER_USD}: auto-renew cannot place a single offer."
fi
if (( ${BFX_AB_A_ARM_TARGET_UST%.*} + ${BFX_AB_B_ARM_AMOUNT_UST%.*} > ${BFX_AB_NAV_UST%.*} )); then
  warn "A + B exceeds NAV — deposit first (ADR D3 suggests NAV ≥ 450), or shrink the split."
fi
write_env BFX_AB_NAV_UST "$BFX_AB_NAV_UST"
write_env BFX_AB_A_ARM_TARGET_UST "$BFX_AB_A_ARM_TARGET_UST"
write_env BFX_AB_B_ARM_AMOUNT_UST "$BFX_AB_B_ARM_AMOUNT_UST"
confirm "Halt confirmed and split accepted — continue?" || { warn "stopped at preflight"; exit 1; }

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Create the sub-account"
say "The B arm lives in its own Bitfinex sub-account so its credits never enter"
say "the bot's full-account reconciliation (I-VTA / I-CAP)."
open_url "https://setting.bitfinex.com/subaccounts"
note "If that URL 404s: Account settings → Sub-Accounts. Sub-accounts need a verified master."
step "Create a sub-account; label it so the purpose is obvious (e.g. ab-frr-b-arm)."
step "Keep its login credentials somewhere safe — you will log in as it in stages 4–5."
ask BFX_AB_SUBACCOUNT_LABEL "Sub-account label exactly as shown:"
write_env BFX_AB_SUBACCOUNT_LABEL "$BFX_AB_SUBACCOUNT_LABEL"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Transfer the B-arm capital (venue write)"
say "This is the only venue write in the setup. Do it under the persistent halt so"
say "the bot's next reconcile simply sees a smaller available balance."
open_url "https://www.bitfinex.com/wallets"
note "Wallets → Transfer: from master Funding wallet (UST) → sub-account ${BFX_AB_SUBACCOUNT_LABEL} Funding wallet."
step "Amount: ${BFX_AB_B_ARM_AMOUNT_UST} UST. Destination wallet type must be Funding (not Exchange)."
confirm "Transfer ${BFX_AB_B_ARM_AMOUNT_UST} UST to ${BFX_AB_SUBACCOUNT_LABEL} now?" || { warn "transfer skipped; re-run to resume"; exit 1; }
pause "Press Enter once Bitfinex shows the transfer completed."
ask BFX_AB_TRANSFER_AT "Transfer time as shown by Bitfinex (UTC, e.g. 2026-09-23 02:15):"
write_env BFX_AB_TRANSFER_AT "$BFX_AB_TRANSFER_AT"
note "Record this venue write in today's daily note (ADR Followup)."

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Enable FRR auto-renew on the sub-account"
say "Log in as the sub-account (or switch to it from the master's sub-account page)."
open_url "https://www.bitfinex.com/funding"
note "Funding → UST → Auto-Renew panel. Rate left blank / FRR, period 2 days, amount fixed to the B arm."
step "Rate: FRR (not a fixed number). Period: 2. Amount: ${BFX_AB_B_ARM_AMOUNT_UST} (fixed, not 'all')."
step "Save, then confirm an offer appears in the sub-account's active funding offers at FRR."
ask BFX_AB_B_ARM_PERIOD "Period configured (must be 2 to match ADR D2):"
if [[ "$BFX_AB_B_ARM_PERIOD" != "2" ]]; then
  warn "period ≠ 2 changes the ADR D2 premise (B arm period 2). Fix it or record the deviation in the ADR."
fi
write_env BFX_AB_B_ARM_PERIOD "$BFX_AB_B_ARM_PERIOD"

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Read-only API key on the sub-account"
say "The loader only reads credits history and ledgers. Grant READ permissions only."
open_url "https://setting.bitfinex.com/api"
note "Create key while logged in as the sub-account. Permissions: Account/Wallets read, Orders read, Funding read. No write, no withdraw."
step "Copy the API key and the API secret (secret is shown once)."
ask_secret BFX_AB_SUBACCOUNT_API_KEY "Paste the sub-account API key:"
ask_secret BFX_AB_SUBACCOUNT_API_SECRET "Paste the sub-account API secret:"
write_env BFX_AB_SUBACCOUNT_API_KEY "$BFX_AB_SUBACCOUNT_API_KEY"
write_env BFX_AB_SUBACCOUNT_API_SECRET "$BFX_AB_SUBACCOUNT_API_SECRET"
note "Stays local in ${ENV_FILE} (gitignored). Do not add it to the bot vault or CI."

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Master-side check and A/B start marker"
say "Back on the master account: nothing new should exist — only a smaller balance."
step "Master active funding offers: unchanged. No orphan/quarantine after the next 90s reconcile."
step "Master fUST available dropped by ${BFX_AB_B_ARM_AMOUNT_UST}."
pause "Press Enter once verified."
BFX_AB_START_MS="$(date +%s)000"
write_env BFX_AB_START_MS "$BFX_AB_START_MS"
note "BFX_AB_START_MS = ${BFX_AB_START_MS} — week 1 of the 8-week window starts at the first Monday 00:00 UTC after this."

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Bookkeeping"
say "Paste these into second-brain so the experiment is traceable:"
say ""
say "  registry (strategy-registry.md, 執行層實驗 row 'bot vs FRR auto-renew A/B'):"
say "    TESTING → RUNNING since $(date -u +%Y-%m-%d), B arm ${BFX_AB_B_ARM_AMOUNT_UST} UST @ FRR p${BFX_AB_B_ARM_PERIOD}, A arm ${BFX_AB_A_ARM_TARGET_UST} UST"
say "  daily: venue write — transfer ${BFX_AB_B_ARM_AMOUNT_UST} UST master → ${BFX_AB_SUBACCOUNT_LABEL} at ${BFX_AB_TRANSFER_AT} UTC (halt id active)"
say ""
warn "A arm earns nothing until lending resumes (wiki Pending 🔴 book WS). B arm accrues from now."
pause "Press Enter when recorded."

finish
