#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
SECRET_DIR="${PGBACKREST_SECRET_DIR:-$HOME/bfx/pgbackrest/conf.d}"
SECRET_FILE="$SECRET_DIR/r2.conf"
ENV_FILE="$SECRET_FILE"

if [[ "$SECRET_DIR" != /* || "$SECRET_DIR" == / ]]; then
  printf '%s\n' "PGBACKREST_SECRET_DIR must be a non-root absolute path." >&2
  exit 1
fi

_prompt_candidate() {
  local variable="$1" option="$2" prompt="$3" hidden="$4"
  local current input
  current=$(_existing "$option" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  if [[ "$hidden" == true ]]; then
    if ! IFS= read -r -s input; then
      printf '\n'
      return 1
    fi
    printf '\n'
  elif ! IFS= read -r input; then
    return 1
  fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$variable" '%s' "$input"
}

_validate_target_shape() {
  if [[ -L "$SECRET_DIR" || ! -d "$SECRET_DIR" ]]; then
    printf '%s\n' "Secret directory must be a real directory." >&2
    return 1
  fi
  if [[ -L "$SECRET_FILE" || ( -e "$SECRET_FILE" && ! -f "$SECRET_FILE" ) ]]; then
    printf '%s\n' "Secret fragment must be a regular file, not a directory or symlink." >&2
    return 1
  fi
  local entry
  for entry in "$SECRET_DIR"/* "$SECRET_DIR"/.[!.]* "$SECRET_DIR"/..?*; do
    [[ -e "$entry" || -L "$entry" ]] || continue
    [[ "$entry" == "$SECRET_FILE" ]] && continue
    [[ -n "$CANDIDATE_DIR" && "$entry" == "$CANDIDATE_DIR" ]] && continue
    printf '%s\n' "Secret directory contains an unexpected direct entry." >&2
    return 1
  done
}

CANDIDATE_DIR=""
CANDIDATE_FILE=""
_cleanup_candidate() {
  if [[ -n "$CANDIDATE_FILE" ]]; then
    rm -f -- "$CANDIDATE_FILE" || true
  fi
  if [[ -n "$CANDIDATE_DIR" && -d "$CANDIDATE_DIR" ]]; then
    rmdir -- "$CANDIDATE_DIR" || true
  fi
}
trap _cleanup_candidate EXIT

existing_endpoint=$(_existing "repo1-s3-endpoint" || true)
existing_account=""
if [[ "$existing_endpoint" =~ ^https://([a-z0-9]{32})\.r2\.cloudflarestorage\.com$ ]]; then
  existing_account="${BASH_REMATCH[1]}"
fi

banner "pgBackRest Cloudflare R2 setup"

stage "Prepare the VM-only R2 fragment"
if [[ -e "$SECRET_DIR" || -L "$SECRET_DIR" ]]; then
  if ! _validate_target_shape; then
    exit 1
  fi
fi
if [[ -n "$existing_account" ]]; then
  R2_ACCOUNT_ID="$existing_account"
  say "Using the account ID from the existing R2 endpoint."
elif ! _prompt_candidate R2_ACCOUNT_ID "" "Cloudflare account ID (32 lowercase characters):" false; then
  printf '%s\n' "Input ended before the candidate fragment was complete." >&2
  exit 2
fi
if [[ ! "$R2_ACCOUNT_ID" =~ ^[a-z0-9]{32}$ ]]; then
  printf '%s\n' "Cloudflare account ID must be 32 lowercase characters." >&2
  exit 1
fi
if ! _prompt_candidate R2_BUCKET repo1-s3-bucket "Terraform-created R2 bucket name (3-63 characters):" false; then
  printf '%s\n' "Input ended before the candidate fragment was complete." >&2
  exit 2
fi
if [[ ! "$R2_BUCKET" =~ ^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$ ]]; then
  printf '%s\n' "Bucket name must be 3-63 lowercase characters." >&2
  exit 1
fi

stage "Create and capture the bucket-scoped R2 token"
open_url "https://developers.cloudflare.com/r2/api/tokens/"
step "Create an R2 API token with Object Read & Write permission."
step "Scope it to the bucket created by Terraform, then copy its Access Key ID."
if ! _prompt_candidate R2_ACCESS_KEY_ID repo1-s3-key "Paste the R2 Access Key ID:" false; then
  printf '%s\n' "Input ended before the candidate fragment was complete." >&2
  exit 2
fi
step "Copy the one-time Secret Access Key without sharing it or saving it elsewhere."
if ! _prompt_candidate R2_SECRET_ACCESS_KEY repo1-s3-key-secret "Paste the R2 Secret Access Key:" true; then
  printf '%s\n' "Input ended before the candidate fragment was complete." >&2
  exit 2
fi

stage "Capture the repository cipher passphrase"
say "This passphrase needs separate offline escrow; loss makes the repository unusable."
if ! _prompt_candidate R2_CIPHER_PASS repo1-cipher-pass "Paste the repository cipher passphrase:" true; then
  printf '%s\n' "Input ended before the candidate fragment was complete." >&2
  exit 2
fi

stage "Protect and validate the fragment"
if [[ ! -e "$SECRET_DIR" ]]; then
  sudo mkdir -p "$SECRET_DIR"
fi
if ! _validate_target_shape; then
  exit 1
fi
CANDIDATE_DIR=$(sudo mktemp -d "$SECRET_DIR/.r2-candidate.XXXXXX")
sudo chown "$(id -u):70" "$CANDIDATE_DIR"
sudo chmod 0750 "$CANDIDATE_DIR"
CANDIDATE_FILE="$CANDIDATE_DIR/r2.conf"
{
  printf '[global]\n'
  printf 'repo1-s3-endpoint=%s\n' "https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
  printf 'repo1-s3-bucket=%s\n' "$R2_BUCKET"
  printf 'repo1-s3-key=%s\n' "$R2_ACCESS_KEY_ID"
  printf 'repo1-s3-key-secret=%s\n' "$R2_SECRET_ACCESS_KEY"
  printf 'repo1-cipher-pass=%s\n' "$R2_CIPHER_PASS"
} | sudo tee "$CANDIDATE_FILE" >/dev/null
sudo chown "$(id -u):70" "$CANDIDATE_DIR" "$CANDIDATE_FILE"
sudo chmod 0750 "$CANDIDATE_DIR"
sudo chmod 0640 "$CANDIDATE_FILE"
python3 "$ROOT/deploy/vm/pgbackrest/secret_validation.py" --secret-dir "$CANDIDATE_DIR"
if ! _validate_target_shape; then
  exit 1
fi
if [[ -f "$SECRET_FILE" ]] && cmp -s "$CANDIDATE_FILE" "$SECRET_FILE"; then
  rm -f -- "$CANDIDATE_FILE"
else
  sudo mv -f -- "$CANDIDATE_FILE" "$SECRET_FILE"
fi
if [[ -n "$CANDIDATE_DIR" ]]; then
  CANDIDATE_FILE=""
  rmdir -- "$CANDIDATE_DIR"
  CANDIDATE_DIR=""
fi
sudo chown "$(id -u):70" "$SECRET_DIR" "$SECRET_FILE"
sudo chmod 0750 "$SECRET_DIR"
sudo chmod 0640 "$SECRET_FILE"
python3 "$ROOT/deploy/vm/pgbackrest/secret_validation.py" --secret-dir "$SECRET_DIR"
say "Validation succeeded without printing secret values."

stage "Install timer definitions"
"$ROOT/scripts/install-pgbackrest-timers.sh"
say "Activation is deferred until the runbook acceptance gates pass."

finish
