[global]
repo1-type=s3
repo1-path=/pgbackrest
repo1-s3-region=auto
repo1-s3-uri-style=path
repo1-block=y
repo1-bundle=y
repo1-cipher-type=aes-256-cbc
repo1-retention-full=4
repo1-retention-diff=6
archive-async=y
start-fast=y
spool-path=/var/spool/pgbackrest
log-path=/var/log/pgbackrest
log-level-file=off
log-level-console=off
log-level-stderr=off

[bfx]
pg1-path=/var/lib/postgresql/18/docker
